### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [nschloe/matplotx#29]
Great package! Thank you so much it really helps!

I will surely use this in my next paper/talk. How can I cite this package?

Do you plan on adding a Zenodo DOI?

Cheers
Remi

**Comment by nschloe** [comment]
> Do you plan on adding a Zenodo DOI?

Sure, I'll do that.

**Comment by nschloe** [comment]
It'll get a DOI at the next release.
